### ISSUE TITLE
Welcome - Here's the plan.

### ISSUE THREAD

**Issue by ghuntley** [planetxamarin/planetxamarin#1]
# Introduction
Readify has an fully fledged RSS aggregator of all of it's employees. When a new employee joins part of their first day on the job is to send in a pull-request to our  aggregator (firehose) for inclusion into our blogroll if they so desire.  The PR looks as follows.

```csharp
    public class GeoffreyHuntley : IAmAReadifarian
    {
        public string FirstName => "Geoffrey";
        public string LastName => "Huntley";
        public string Title => "Lead Consultant";
        public string StateOrRegion => "NSW";
        public string EmailAddress => "geoffrey.huntley@readify.net";
        public string TwitterHandle => "geoffreyhuntley";

        public Uri WebSite => new Uri("https://ghuntley.com/");
        public IEnumerable<Uri> FeedUris { get { yield return new Uri("https://ghuntley.com/atom.xml"); } }
    }
```

# The Proposal

* Readify releases the source code under appropriate license (MIT/MS-PL/Whatever that's not GPL)
* We work together to create `github.com/xamarin/firehose` which is hosted at https://firehose.xamarin.com/
* It's hosted on Microsoft Azure by Xamarin and merged pull-requests results automatic deployments into production.
* When it's unveiled Readify asks for a quick plug in the blogpost  (see http://www.arnnet.com.au/article/583877/interview-readify-managing-director-graeme-strange/ for more info about Readify) - James if this is going to be contentious then please speak with me privately. It's a ask/acknowledgement type thing.

We implement three interfaces that use a contract similar to above.

* IWorkAtXamarin
* IAmAnXamarinMVP
* IAmAComunityMember

We expose a mixture of end-points:

* An endpoint that is everyone in the firehose.
* An endpoint that is just Xamarin employees
* An endpoint that is just Xamarin MVPs
* An endpoint that is just Community.

# Screenshots

![screencapture-firehose-labs-readify-net-whoarewe-readifarians-1478575269245](https://cloud.githubusercontent.com/assets/127353/20085660/a8945bd4-a5be-11e6-987f-e49889813e92.png)

![image](https://cloud.githubusercontent.com/assets/127353/20085685/d8bc777e-a5be-11e6-955d-388f44f3addd.png)

![screencapture-firehose-labs-readify-net-1478575312018](https://cloud.githubusercontent.com/assets/127353/20085673/ba559c02-a5be-11e6-9965-eedaa7799b43.png)

# Website

https://firehose.labs.readify.net/

**Comment by ghuntley** [comment]
@jfversluis invitation has been sent!

Here's the next steps:

- Complete ordering of SSL certificate  #13 
- Host the website on Azure w/PaaS website #4 
- Configure Azure PaaS website to automatically deploy from this source code #5

**Comment by jamesmontemagno** [comment]
@ghuntley  Do you just need me to do stuff. we should close out all old stuff and assign stuff to me. I can try to finish all this week.

**Comment by ghuntley** [comment]
@jamesmontemagno do the stuff in https://github.com/ghuntley/planetxamarin/issues/1#issuecomment-272755848 and then we can "launch".
