### ISSUE TITLE
IFTTT -> Twitter/Facebook

### ISSUE THREAD

**Issue by jamesmontemagno** [planetxamarin/planetxamarin#10]
ChrisNTR had this setup before and can have him do it again.

**Comment by jamesmontemagno** [comment]
@ghuntley I just need the final feed URLs so I can set this up.

**Comment by ghuntley** [comment]
Final URL is now `http://www.planetxamarin.com/feed`

**Comment by jamesmontemagno** [comment]
Implemented

**Comment by ghuntley** [comment]
omg yus 🎉 

![image](https://cloud.githubusercontent.com/assets/127353/22040000/74648112-dd55-11e6-90ac-08bc11130b95.png)


![image](https://cloud.githubusercontent.com/assets/127353/22040007/7b072ccc-dd55-11e6-92f7-e992649882ee.png)
