### ISSUE TITLE
Author info not coming through in Preview

### ISSUE THREAD

**Issue by dvolvenl** [planetxamarin/planetxamarin#105]
I've noticed this before as I was working on the styling but most of the `SyndicationItems` in the Preview feed don't have author information available. Some claim to have an emailaddress but it is not an actual emailaddress (see screenshot).

To make the preview screen worth it it'd be nice to see who posted what.

![capture](https://cloud.githubusercontent.com/assets/2419439/22075219/679e50f6-ddab-11e6-82f8-a9b3ec1b478a.png)

**Comment by jamesmontemagno** [comment]
Looks good to me now! <3 Nice!

**Comment by dvolvenl** [comment]
This was fixed with #109 and even better with #110.
