### ISSUE TITLE
Cleaning up the content of Preview

### ISSUE THREAD

**Issue by sthewissen** [planetxamarin/planetxamarin#111]
There's a lot of stuff going on in the preview page:

1. Posts where the entire post is in the description
2. Posts with no description
3. Posts with code blocks or blockquotes in the description
4. Posts with additional components (such as Feedburner) mixed in

Ideally you would simply get a nice excerpt of each blog post without all the extra stuff mentioned above.

**Comment by dvolvenl** [comment]
One option I'm working on atm is stripping out HTML using Regex and taking a predetermined amount of characters from what remains. To avoid truncating mid sentence I'm looking for the next "." character and truncating from there onwards. It wouldn't tackle nr 2 in the above list, but it would be a start I suppose. Comments?

**Comment by dvolvenl** [comment]
A start for the above was made in #119.
