### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by ghuntley** [planetxamarin/planetxamarin#13]
I've ordered an SSL certificate (MVP's get free SSL certs) and need @jamesmontemagno to click on the verification email that should have arrived moments ago in his inbox. 

![image](https://cloud.githubusercontent.com/assets/127353/21968306/6a3170f2-dbe7-11e6-8fae-41386b169d08.png)

After the verification has been approved @ghuntley needs to generate a certificate and provide it to @jamesmontemagno who will then need to install it into the Azure website PaaS.

Related issue: #4

**Comment by jamesmontemagno** [comment]
Approved and good to go. I need to install the azure site... hmmm

**Comment by jfversluis** [comment]
Another way to go about this it by [this guide](https://www.troyhunt.com/how-to-get-your-ssl-for-free-on-shared/) by Troy Hunt. This would involve a free CloudFare account and there is no dependence on who is or isn't an MVP and the SSL being renewed. We've used it for snppts.io and it works really well!

**Comment by ghuntley** [comment]
@jfversluis that works as well. I use that for ghuntley.com. Because this website doesn't transmit any credentials using cloudflare like that is acceptable. @jamesmontemagno if you have a cloudflare account set it up that way, or we can use the SSL cert but we will need to reinstall a new certificate in 365 days.

**Comment by jamesmontemagno** [comment]
I will create the account today ;)

**Comment by jamesmontemagno** [comment]
Cloudflare setup and complete, we are good now on this.

**Comment by jamesmontemagno** [comment]
Waiting for DNS to figure itself out.

**Comment by ghuntley** [comment]
This now works; thanks!
