### ISSUE TITLE
i18n / internationalization

### ISSUE THREAD

**Issue by ghuntley** [planetxamarin/planetxamarin#16]
Thoughts:

- Don't localize the RSS aggregator website.
- Extend the interfaces to add support for languages. i.e. (`zh-CN`)
- Provide way for consumers of the RSS feed to exclude languages that the consumer does not know.
- Provide way for consumers of the RSS feed to get only languages that the consumer knows.

**Comment by jamesmontemagno** [comment]
Hmmmm seems like too much. Keep it simple

**Comment by jfversluis** [comment]
Implemented in #429 so this should be resolved!
