### ISSUE TITLE
Preview and RSS feed pages are breaking on https://www.planetxamarin.com/

### ISSUE THREAD

**Issue by manojkulkarni30** [planetxamarin/planetxamarin#167]
On live site https://www.planetxamarin.com/ following pages are breaking:
- https://www.planetxamarin.com/preview
- https://www.planetxamarin.com/feed
Displaying yellow screen.

**Comment by jfversluis** [comment]
You're right! Looks like one feed is ruining it for the rest of us.
Let me see if I can fix that!

**Comment by jfversluis** [comment]
Hm it only happens in the live environment. Locally there doesn't seem to be any problem

**Comment by jfversluis** [comment]
Fixed for now by #168 but I think we need to put in some more effort to not let one blog take down our feed. Will take that into a next issue.
