### ISSUE TITLE
Make getting feeds more stable

### ISSUE THREAD

**Issue by jfversluis** [planetxamarin/planetxamarin#169]
In follow-up of #167 I think we need to take a closer look at how to not let one unstable feed break our page. One authors blog was down and returned a 403 which broke our preview and feed page, so mainly our core business.

I have implemented some logic to catch an exception like this at a high level (see #168) but I think we can add some more logic to make it more stable.

**Comment by jfversluis** [comment]
My idea would be something [like this](https://github.com/planetxamarin/planetxamarin/compare/loadingfeed-enhancing?expand=1), thoughts?

Not sure if we should lose the dummy variable then, maybe that is a bit redundant and slowing it down now unnecessarily.

**Comment by jamesmontemagno** [comment]
We had this issue with the old planet where sometimes sites were down or moved domains, so worth fixing this up sooner then later.
