### ISSUE TITLE
Investigate why this tweet didn't have a URL

### ISSUE THREAD

**Issue by ghuntley** [planetxamarin/planetxamarin#178]
https://twitter.com/PlanetXamarin/status/823537090315124737

**Comment by jamesmontemagno** [comment]
It is too long :(

**Comment by jamesmontemagno** [comment]
I have changed it to just:
{{EntryTitle}} {{EntryUrl}}

If the Entry Title is too long it will still have this problem though.

**Comment by ghuntley** [comment]
Could you adjust it to be `{{EntryTitle}} {{EntryUrl}} #xamarin` that way tweets that are short enough have the xamarin hashtag for discovery?

**Comment by jamesmontemagno** [comment]
The #Xamarin would actually take up space and IFTTT doesn't add the URL it is too long. It used to add #Xamarin at the very end but it didn't add the URL as you can see.

**Comment by jamesmontemagno** [comment]
I can adjust it to whatever you think... Probably #Xamarin is okay.... the author name was probably too much

**Comment by ghuntley** [comment]
Agree; drop the author name. 

Let's try 🚢 `{{EntryTitle}} {{EntryUrl}} #xamarin` :shipit: 

If this continues to be a problem then this would work - but it's ugilier.

`{{EntryUrl}} #xamarin {{EntryTitle}}`

**Comment by jamesmontemagno** [comment]
sounds good
