### ISSUE TITLE
Page Error on /Preview section

### ISSUE THREAD

**Issue by stvansolano** [planetxamarin/planetxamarin#189]
**Host:** RD000D3A13574A
**Code:** 0
**Type:** InvalidOperation
**Date/Time:** 1/26/2017	12:28 AM
**Details:** The view 'Error' or its master was not found or no view engine supports the searched locations. The following locations were searched: ~/Views/Feed/Error.aspx ~/Views/Feed/Error.ascx ~/Views/Shared/Error.aspx ~/Views/Shared/Error.ascx ~/Views/Feed/Error.cshtml ~/Views/Feed/Error.vbhtml ~/Views/Shared/Error.cshtml ~/Views/Shared/Error.vbhtml

[More](https://www.planetxamarin.com/logs/detail?id=908ab4ce-c89c-450f-bfaa-9129566e2d9a)

**Comment by jamesmontemagno** [comment]
Working now, putting in additional fixes to help this

**Comment by stvansolano** [comment]
Awesome! Working file so far.

**Comment by stvansolano** [comment]
Oops, still reproducible today @jamesmontemagno
