### ISSUE TITLE
Remove "Email" Address and put in Gravatar Hash

### ISSUE THREAD

**Issue by jamesmontemagno** [planetxamarin/planetxamarin#19]
We should tell people to use: https://en.gravatar.com/site/check/ instead of putting in email as that is sensitive.

**Comment by jamesmontemagno** [comment]
My work email is everywhere, but I usually hide personal email address. It is mostly around people skimming for emails and signing up for it. It is all we are really using the email for. I highly recommend not making it required. I think the GravatarHash is all we need.

**Comment by jfversluis** [comment]
With the merge of #30 this should be resolved, you can keep your email to yourself @jamesmontemagno ! ;)
