### ISSUE TITLE
RSS Feed and Profile Tabs Broken

### ISSUE THREAD

**Issue by JaridKG** [planetxamarin/planetxamarin#192]
The RSS Feed and the profile tabs on https://www.planetxamarin.com/ redirect to "Server Error in '/' Application."

When running and clicking on feed in Visual Studio im getting a System.XML.XMLException on line 24 of the CombinedFeedSource.cs that {"'atom' is an undeclared prefix. Line 6, position 6."}

**Comment by jamesmontemagno** [comment]
We are investigating

**Comment by stvansolano** [comment]
Same for /Preview, still happens #189

**Comment by jamesmontemagno** [comment]
Fixed for the time being.
