### ISSUE TITLE
Investigate Issues with Bad Blogs Taking down Planet

### ISSUE THREAD

**Issue by jamesmontemagno** [planetxamarin/planetxamarin#195]
Temporarily had to take down:
@jfversluis  investigated with:

Alexandr Sorokoletov, Alois Deniel and GoneMobile were causing issues. Infestigating.

Also,
- Glenn Versweyveld (http://depblog.weblogs.us/feed/) returns a 403, although the browser return OK. Since I know him I’ve discussed it and he is looking into it.
- Nuno Horta (https://www.nunobhorta.com/feed/) gives a non trusted ssl connection
- Malcolm Jack (http://inquisitorjax.blogspot.co.za/feeds/posts/default?alt=rss) gives a timeout, might have been a one-time thing

We must implement some way to validate and ensure bad blogs don't take it down.

**Comment by alexsorokoletov** [comment]
@jamesmontemagno is there any information what is wrong and how can I help?
I am using github pages + jekyll for the website, https is valid

**Comment by alexsorokoletov** [comment]
@jamesmontemagno indeed, problem was that the feed.xml was not parseable (I posted an article about Func<T>, guess what went wrong with the parsing).
Feed is fixed, but the thing is that any incorrect xml will basically ruin whole thing.
