### ISSUE TITLE
Issues with IAmAMicrosoftMVP

### ISSUE THREAD

**Issue by kjacobsen** [planetxamarin/planetxamarin#202]
Hi,

Noticed this with Planet PowerShell, and also saw it in Planet Xamarin.

Whilst the readme for both projects asks Microsoft MVPs (and Xamarin MVPs) to use the ```IamAMicrosoftMVP``` interface and to specify ```IAmAMicrosoftMVP.FirstAwarded```, this results in the build failing.

I will create a PR to resolve the interface definition.

**Comment by Cheesebaron** [comment]
It is just the readme that needs to be updated to reflect the changes here. The dates are not used for anything.

**Comment by kjacobsen** [comment]
I will raise a new PR with the update for the readme.
