### ISSUE TITLE
Profile image blank/default

### ISSUE THREAD

**Issue by almirvuk** [planetxamarin/planetxamarin#226]
Hi,

Under section: https://www.planetxamarin.com/authors on the map when you zoom to the Italy or Bosnia and Herzegovina you can see me around the Mostar and the circle image is default dummy one, but when you click on it it navigate (scroll down) to the my info and image is Ok, is this some bug or what?

Best regards!
![image](https://cloud.githubusercontent.com/assets/15986629/23344283/f972b106-fc79-11e6-9e54-f665172694b0.png)

**Comment by Cheesebaron** [comment]
Shows up fine here.

![image](https://cloud.githubusercontent.com/assets/249719/23344404/08f0b900-fc7c-11e6-9db1-8b981545010a.png)

**Comment by almirvuk** [comment]
Yes and it is the same... here is my friend tried also and his result:
![image](https://cloud.githubusercontent.com/assets/15986629/23371161/776f1dfe-fd17-11e6-8624-5c7592bda125.png)

**Comment by jfversluis** [comment]
Seems OK on my end as well. By any change you and your friend share a internet connection on which something is cached in a proxy or something?

**Comment by almirvuk** [comment]
Hi @jfversluis, no he is in a another different city. :(

**Comment by jfversluis** [comment]
That's weird, what happens when you get the URL out of the source and load it directly into your browser? Does it only happen on mobile or everywhere?

**Comment by Cheesebaron** [comment]
It is just a gravatar url, should work fine.

**Comment by almirvuk** [comment]
Yea gravatar url is Ok, it show in the details bellow the map, my avatar down bellow is Ok but on map is this dummy icon.

**Comment by jfversluis** [comment]
I am going to assume that this issue was an incident. If something still is wrong, feel free to reopen or comment.
