### ISSUE TITLE
BlogMonster is slow 🐌 

### ISSUE THREAD

**Issue by Cheesebaron** [planetxamarin/planetxamarin#230]
Building the feed after having checked for broken feeds takes between 2 and 3 minutes.

It is freakishly slow as fetching the feeds themselves takes less than 15 seconds when done correctly. To me it seems like BlogMonster is not running parallel inside of its belly.

**Comment by Cheesebaron** [comment]
This was kind of mitigated in #229 

However, I have some ideas I want input on, that I have vented a bit on Slack. Currently, I don't like the idea that a request to the webpage generates the feed if the cache is timed out, as this still takes around a minute or so, and will take longer and longer, the more feeds we aggregate.

So I see two alternatives:

1. Add a database to the mix and dump people's feeds into that. There are however some issues with this approach, such as if the person deletes their post, or if they edit it, we need to react to it.
2. The other approach is to have a background worker, which kicks in every X interval, say 1 hour, goes through all the feeds etc. in the background, without any performance implications of the webpage or the feed. Then when it is ready and has done its job, it simply replaces the feed with a new version. This way we could, if we really wanted also switch to a static webpage. 

I really like the idea of 2. as it keeps the feeds fresh, we don't duplicate people's data. No need to keep track of things, and it does not have any performance hit on the webpage.

Do any of you have better ideas or other thoughts?

**Comment by Cheesebaron** [comment]
@planetxamarin/owners missing some feedback here.

**Comment by ghuntley** [comment]
Keep PlaentXamarin stateless is my vote.and preference. Having a webjob that updates the feedservice and making page load events query feedservice is a solid idea. Easy to implement as well.

**Comment by jfversluis** [comment]
I'm with you on this with you guys. I still very much like how we are adding people and the open character it has right now. So as long as it is humanly possible I think we should keep it that way.
