### ISSUE TITLE
Blog date not restricted to present

### ISSUE THREAD

**Issue by JaridKG** [planetxamarin/planetxamarin#239]
If a blog writes an entry with a future date it keeps it at the top until that date occurs
<img width="335" alt="screen shot 2017-03-14 at 2 13 58 pm" src="https://cloud.githubusercontent.com/assets/5750446/23922681/897d0ca4-08c0-11e7-99e4-db23b66ed5ff.png">
<img width="311" alt="screen shot 2017-03-14 at 2 14 13 pm" src="https://cloud.githubusercontent.com/assets/5750446/23922680/897bb0f2-08c0-11e7-867e-f11116b1d998.png">

**Comment by Cheesebaron** [comment]
Thank you for reporting this. It should obviously not happen, this way it can be abused.

**Comment by mattleibow** [comment]
I just want to mention that this is still happening (obviously) and we should do something about it...

**Comment by jfversluis** [comment]
Code is merged now and should not happen again!
