### ISSUE TITLE
My pull request was approved, but I don't show up

### ISSUE THREAD

**Issue by JesseLiberty** [planetxamarin/planetxamarin#284]
Hope this is the right place to put this.  My pull request was approved a month or more ago, but I don't show up in the authors.  thanks.

public class JesseLiberty :IAmACommunityMember, IAmAXamarinMVP, IFilterMyBlogPosts
{
  public string FirstName => "Jesse";
  public string LastName => "Liberty";
  public string ShortBioOrTagLine => "See http://jesseliberty.me";
  public string StateOrRegion => "Massachusetts";
  public string EmailAddress => "jesseliberty@gmail.com";
  public string TwitterHandle => "jesseliberty";
  public string GravatarHash => "78d5b6609fe5a80ce67e9f971833a6c3";
  public string GitHubHandle => "JesseLiberty";
  public GeoPosition Position => new GeoPosition(42.4703963,-71.4477468,15);
  public Uri WebSite => new Uri("http://jesseliberty.me");
  public IEnumerable(Uri) FeedUris { get { yield return new Uri("http://feeds.feedburner.com/JesseLiberty-SilverlightGeek");
  
   public bool Filter(SyndicationItem item)
    {
        // This filters out only the posts that have the "xamarin" category
        return item.Categories.Any(c => c.Name.ToLowerInvariant().Equals("xamarin"));
    }
  }

**Comment by jfversluis** [comment]
Could it be that you forgot to add the class to the csproj file? :)

**Comment by JesseLiberty** [comment]
@jfversluis Can you say a bit more?  Thanks.

**Comment by jfversluis** [comment]
Besides implementing the class, you will have to add t to the csproj file so it is picked up at build-time.

Somewhere around here, like the other ones; https://github.com/planetxamarin/planetxamarin/blob/master/src/Firehose.Web/Firehose.Web.csproj#L243

**Comment by JesseLiberty** [comment]
I'm sure that was it, thanks!
