### ISSUE TITLE
How to be included in Xamarin Planet?

### ISSUE THREAD

**Issue by deanilvincent** [planetxamarin/planetxamarin#301]
Good day guys, I'm having some trouble on adding myself on Xamarin Planet as one of the bloggers. I love creating Xamarin Blogs, Tutorials and Community Tech talks. Here's my .cs file photo

![screen shot 2017-07-15 at 7 24 42 pm](https://user-images.githubusercontent.com/10904957/28239003-538adcbe-6993-11e7-86c0-4a67cabed974.png)

I need some help thank you so much! :)

**Comment by jfversluis** [comment]
Hi!

Great you want to be a part of our little community! Unfortunately, you didn't say with what you are having trouble. What is going on? What is not working? Do you receive any errors?

Thanks!

**Comment by deanilvincent** [comment]
Honestly, I don't know where can I pull request? :)

**Comment by Cheesebaron** [comment]
Are you asking how to make a Pull Request on GitHub?

**Comment by deanilvincent** [comment]
I already forked it to my github profile and created pull request there.

**Comment by Cheesebaron** [comment]
You need to make the pull request against this repository, and actually modify the files needed to be included, instead of just posting the code as a comment.

**Comment by deanilvincent** [comment]
@Cheesebaron  yes, I already created a pull request using terminal 

![screen shot 2017-07-17 at 11 10 16 am](https://user-images.githubusercontent.com/10904957/28254577-8eef953a-6ae0-11e7-9097-6b235225c30f.png)

**Comment by jfversluis** [comment]
Maybe this guide will help; https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by deanilvincent** [comment]
Thank you so much @jfversluis  I was just following this link: http://kbroman.org/github_tutorial/pages/fork.html Yeah, if we stop learning, it's like we're limiting our own self. By the way, I successfully created the pull request. :)

**Comment by jfversluis** [comment]
Great! Let me close this issue, as this is done now.
I see some issues with your code, but we will discuss that in the PR. Great that you got it to work!
