### ISSUE TITLE
More information to profile

### ISSUE THREAD

**Issue by martijn00** [planetxamarin/planetxamarin#33]
What about adding developer profile information to the `IAmACommunityMember` such as:

* Github
* StackOverflow
* LinkedIn
* Xamarin forums

It would make it easier to find certain resources.

**Comment by ghuntley** [comment]
Let's see how #7 evolves first.

**Comment by martijn00** [comment]
I guess it depends on the design if the cards would get bigger or not. It would be possible to do more awesome things with that information, but for now only that it would show up is an improvement imo.

**Comment by jamesmontemagno** [comment]
I think github would be great for sure ;)

**Comment by jamesmontemagno** [comment]
I agree that the idea isn't really about the website it is more about the RSS so let focus on that.
