### ISSUE TITLE
Filter logic not working?

### ISSUE THREAD

**Issue by patridge** [planetxamarin/planetxamarin#341]
I just published a blog post about Netduino that I didn't intend to have feed to the Planet Xamarin Twitter account, but it [still did](https://twitter.com/PlanetXamarin/status/907255750430478337)…sorry.

I'm curious if the `Filter(SyndicationItem item)` logic is being fired correctly or if I screwed something up in my logic.

This is the currently `Filter` on my blog:

```csharp
public bool Filter(SyndicationItem item) =>
        item.Title.Text.ToLowerInvariant().Contains("xamarin") ||
        item.Categories.Any(category => category.Name.ToLowerInvariant().Contains("xamarin"));
```

Here is the current relevant [feed item fields](http://www.patridgedev.com/feed/) for the post in question, which don't appear to have "xamarin" in them anywhere:

```xml
…
<title>Return of Netduino, .NET on small hardware</title>
…
<category><![CDATA[dev]]></category>
<category><![CDATA[c#]]></category>
<category><![CDATA[netduino]]></category>
…
```

**Comment by Cheesebaron** [comment]
Hmm, yeah, that is strange. Need to look into that. It is supposed to work.

**Comment by Cheesebaron** [comment]
Just checked. Your author class does not implement `IFilterMyBlogPosts`. Add that interface and you should be good next time 😄
