### ISSUE TITLE
New blogpost not picked up

### ISSUE THREAD

**Issue by PieEatingNinjas** [planetxamarin/planetxamarin#389]
Hey guys! 
My last blogpost from yesterday is not being picked up by PlanetXamarin. @jfversluis already looked into it and he could see that there was an exception in the logs when the application tries to connect to [my rss feed](https://blog.pieeatingninjas.be/feed/rss). However, I am able to successfully open my rss feed in the browser and don't see any certificate errors or anything.

Anybody an idea?

@jamesmontemagno do you see any additional issues or logs on your Azure subscription where the application is hosted? 

Thanks for your help!

**Comment by Cheesebaron** [comment]
Thanks for reporting this. I think this might be due to our code currently not supporting TLS 1.2. I'll take a look later tonight.
