### ISSUE TITLE
Who's going to host this? Where?

### ISSUE THREAD

**Issue by ghuntley** [planetxamarin/planetxamarin#4]
ITT @jamesmontemagno lays down the plan for hosting this.

**Comment by ghuntley** [comment]
See https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-custom-domain-name for instructions how to configure the PaaS website w/ the domain name.

**Comment by jamesmontemagno** [comment]
DONE!: https://communityplanetxamarin.azurewebsites.net/

**Comment by ghuntley** [comment]
Opening this up again.

http://planetxamarin.com/ = 404
https://planetxamarin.com/ = 404

https://www.planetxamarin.com/ = good
http://www.planetxamarin.com/ = good

Please add the alias @jamesmontemagno  in Azure

**Comment by jamesmontemagno** [comment]
Added, should be up soon. Had to add in some A records

**Comment by jamesmontemagno** [comment]
And we are live!

**Comment by jamesmontemagno** [comment]
Hmmmm... I am not sure what is going on. As both validated in Azure and cloudflare... does cloudflare support the non www. or do I have to setup a redirect?

**Comment by ghuntley** [comment]
DNS is just trolling you; works fine downunder.

**Comment by jamesmontemagno** [comment]
oh nice, classic
this is good
