### ISSUE TITLE
New post now showing on PlanetXamarin feed.

### ISSUE THREAD

**Issue by DanielCauser** [planetxamarin/planetxamarin#415]
Hey guys!

The post I just published on my blog is not showing up on Planet Xamarin blog feed. Could someone check this out?

[This is my new post](https://causerexception.com/2018/02/06/xamarin-forms-ultimate-horizontal-list-guide/)

**Comment by Cheesebaron** [comment]
@DanielCauser what time did you post it? We cache the feed for an hour.

**Comment by DanielCauser** [comment]
Hi @Cheesebaron ! I posted it an hour 1h and 45min ago =/

**Comment by Cheesebaron** [comment]
Will give the debugger a spin to see what is going on :)

**Comment by Cheesebaron** [comment]
There your post should appear soon.

#416

**Comment by Cheesebaron** [comment]
Seems like it made the RSS feed now :) Tweet will be spit out by the IFFFT bot soon.
