### ISSUE TITLE
Blogpost appear twice

### ISSUE THREAD

**Issue by yuv4ik** [planetxamarin/planetxamarin#443]
For some reason my [last blogpost](https://smellyc0de.wordpress.com/2018/03/09/using-native-facebook-login-button-in-xamarin-forms/) appears twice in the feed.

I defined two different FeedUris, one for Xamarin and one for Xamarin.Forms, this blogpost appear in both. Most probably this is the reason.

Possible solution: filter by item/guid

I will take a look on the source.

P.S.: Auto-tweeting worked as expected.

**Comment by yuv4ik** [comment]
Implemented a fix in #444

**Comment by Cheesebaron** [comment]
It is probably because you have two feeds containing the same items. However, we should handle this gracefully. I see your PR helps with that.
