### ISSUE TITLE
PlanetXamarin stopped deploying new builds

### ISSUE THREAD

**Issue by Cheesebaron** [planetxamarin/planetxamarin#466]
For some reason PlanetXamarin stopped deploying new builds on April 3. Didn't notice this until now.

Can @planetxamarin/owners with rights to the Azure instance or whatever we deploy to look at what is going on? I don't have access to that stuff.

**Comment by ghuntley** [comment]
The azure sub belongs to James.

**Comment by Cheesebaron** [comment]
@jamesmontemagno could you please take a look at what is up? If you need any help speak up.

**Comment by jamesmontemagno** [comment]
Looking into it.

**Comment by jamesmontemagno** [comment]
it is doing weird auto deploys from azure... i have no idea how it works to be honest

**Comment by jamesmontemagno** [comment]
don't change if it isn't broken lol
let me research

**Comment by jamesmontemagno** [comment]
i can probably just set it up in VSTS.

**Comment by jamesmontemagno** [comment]
For some reason it isn't showing that I own this repo or the org.... strange.

**Comment by jamesmontemagno** [comment]
I configured it with just normal https, should be good now, however I would like to know why it isn't showing up in my list of owned repos... as I could tie in CI closer to it.

**Comment by Cheesebaron** [comment]
Are you using a personal access token? Maybe you didn't give that enough permissions?
