### ISSUE TITLE
Restrict IFTTT feed to English content

### ISSUE THREAD

**Issue by jfversluis** [planetxamarin/planetxamarin#481]
As per this Twitter thread; https://twitter.com/PlanetXamarin/status/998550843648552960

The possibilities to filter are there, just needs to be added to the Twitter/FB feed

**Comment by jamesmontemagno** [comment]
What is the rss feed to consume?

**Comment by jfversluis** [comment]
Whoops, that would be: https://www.planetxamarin.com/feed?lang=en

**Comment by jamesmontemagno** [comment]
Done!
