### ISSUE TITLE
New authors not deployed

### ISSUE THREAD

**Issue by johnthiriet** [planetxamarin/planetxamarin#487]
I have been added for about 3 weeks now and I still do not show up on the website.
Build went fine though, a problem with deployment ?

**Comment by johnkwaters** [comment]
I have the same issue.

**Comment by jamesmontemagno** [comment]
I am looking into this :)

**Comment by Cheesebaron** [comment]
@jamesmontemagno if you need help I am available.

**Comment by jamesmontemagno** [comment]
Should be good, i forgot to turn on the CI check box lol
