### ISSUE TITLE
GoneMobile.io: Not updated

### ISSUE THREAD

**Issue by Redth** [planetxamarin/planetxamarin#512]
Looks like https://github.com/planetxamarin/planetxamarin/blob/master/src/Firehose.Web/Authors/GoneMobile.cs#L20 is not updating correctly... We have ~3 items missing on planetxamarin.com.

Everything looks correct (nothing's changed) on our end...

Help would be appreciated!

**Comment by jamesmontemagno** [comment]
Are you using xamarin as a tag?

We now force this as a tag: https://github.com/planetxamarin/planetxamarin/blob/11a75d8143962e7bb3fae446ed39fed959f34d72/src/Firehose.Web/Extensions/SyndicationItemExtensions.cs

**Comment by jamesmontemagno** [comment]
Ah... I am curious if itunes:keywords aren't getting picked up....

**Comment by jamesmontemagno** [comment]
My fix will now pickup these keywords. You can set them in fireside.
