### ISSUE TITLE
Query regarding terms of adding new author

### ISSUE THREAD

**Issue by dev-aritra** [planetxamarin/planetxamarin#528]
Is it necessary to have a blog which is running for 6 months or more?
I just started blogging, will I be eligible to make a request to be added as an author when I complete the first 3 articles?
Please let me know.

Thank you.

**Comment by jfversluis** [comment]
We did put in the rule for 6 months to prevent authors from quickly drafting up three article, getting into Planet Xamarin and then abandoning their blog. Of course, I am not saying you will do this, but from past (own) experience I/we know that blogging consistently over a longer period of time is hard.

That is why we put up the rule, to prevent all kinds of "three post blog websites" signing up while they do not produce any content. As far as I am concerned it doesn't have to be 6 months to the day, but as long as we see content over a longer period of time it should be OK.

However, that does mean that you won't directly be eligible when you create three posts right now and submit. Please work on amazing content and try it in a few months 🙂

**Comment by dev-aritra** [comment]
Ahh, alright @jfversluis , will keep writing and come back in few months. Thanks for the clarification.
Cheers.
