### ISSUE TITLE
Official RSS Feed

### ISSUE THREAD

**Issue by jamesmontemagno** [planetxamarin/planetxamarin#54]
Is it: 
http://www.planetxamarin.com/Feed/Rss/50

or just:
http://www.planetxamarin.com/Feed/Rss

The front page links to the first one

**Comment by ghuntley** [comment]
This blocks launch; I'd prefer to have .com/feed but what about #9 (exposure of one or more feeds). Figure out #9 first then come back here.

**Comment by jamesmontemagno** [comment]
I posted my comments in there. I am not sure how hard it is to do multiple feeds. If it is super easy then sure have separate I guess. Else one master feed is probably fine.

Is it easy to change the master feed to just /feed ?

**Comment by ghuntley** [comment]
As of #76 we now have

- /preview to display an RSS preview
- /authors to display who our authors are
- /feed is what your RSS reader subscribes to

A consumer of the aggregator can either point their reader to https://www.planetxamarin.com/ (and the metadata will automatically redirect to https://www.planetxamarin.com/feed/)
