### ISSUE TITLE
Usergroup YouTube Videos

### ISSUE THREAD

**Issue by ahoefling** [planetxamarin/planetxamarin#566]
I want to add our UserGroup Blog as we post a recorded youtube video every month of the session. Would this be something that we can add to Planet Xamarin?

**Comment by Cheesebaron** [comment]
Sure, that should be fine. Look at https://github.com/planetxamarin/planetxamarin/blob/master/src/Firehose.Web/Authors/HoussemDellai.cs how to set it up

**Comment by jfversluis** [comment]
Yep, I don't see why not!

**Comment by ahoefling** [comment]
Great, thanks for the feedback and examples
