### ISSUE TITLE
Authors not meeting policy

### ISSUE THREAD

**Issue by nickrandolph** [planetxamarin/planetxamarin#580]
**Describe the bug**
Two authors are no longer meeting the requirements:
@gptucci
@robinmanuelthiel

**To Reproduce**
Build is failing on All_Authors_Have_Secure_And_Parsable_Feed unit test

**Expected behavior**
All_Authors_Have_Secure_And_Parsable_Feed unit test should pass

**Screenshots**
N/A

**Comment by gptucci** [comment]
I've solved the issue in my website - @gptucci
Tnx

**Comment by nickrandolph** [comment]
Thanks @gptucci 
@robinmanuelthiel as we've had no response, I'll remove you from the authors list in the next PR

**Comment by nickrandolph** [comment]
@gptucci please see the CI build for https://github.com/planetxamarin/planetxamarin/pull/581 - it's failing because you're feed doesn't contain enough posts that it recognises are about Xamarin.
