### ISSUE TITLE
Document how to an author can configure a filter that restricts their feed to only xamarin posts

### ISSUE THREAD

**Issue by ghuntley** [planetxamarin/planetxamarin#6]
```
namespace Firehose.Web.Authors
{
    public class AndrewHarcourt : IAmAReadifarian, IFilterMyBlogPosts
    {
        // TODO: Fill in all your details
        // TODO implement the Filter method any way you like :)
    }
}
```

**Comment by ghuntley** [comment]
@jfversluis your template was merged into https://github.com/ghuntley/planetxamarin earlier this morning. We still need some more information / examples how to filter categories then this issue can be closed.

**Comment by jfversluis** [comment]
Added the main idea of this with #32 and thus can be closed
