### ISSUE TITLE
Featured Community Blog badge

### ISSUE THREAD

**Issue by jfversluis** [planetxamarin/planetxamarin#61]
@jamesmontemagno are we allowed to give out the badge as well?

![Badge](https://blog.verslu.is/wp-content/uploads/2015/04/CommunityFeaturedPlanet1.png)

If so, I'll add it at a few logical places

**Comment by jamesmontemagno** [comment]
YUP! Do it!

**Comment by jfversluis** [comment]
We're back baby!
