### ISSUE TITLE
Force SSL

### ISSUE THREAD

**Issue by jfversluis** [planetxamarin/planetxamarin#63]
While SSL is in place the user isn't routed there by default.
Shouldn't we always want to use SSL?

**Comment by ghuntley** [comment]
Working on this now, I broked the 302 redirect logic.

**Comment by ghuntley** [comment]
Ugh. I give up for now. @jfversluis can you take a lookie? I'll move onto something else.

**Comment by jfversluis** [comment]
@jamesmontemagno It seems to work locally but not on the PRD webserver, any configuration there that overwrites our rewrite rules?

**Comment by jamesmontemagno** [comment]
I am using cloudflare for this... not sure exactly what the steps are here... let me look. Is it in azure?

**Comment by ghuntley** [comment]
@jamesmontemagno oh that's a good idea. In cloudflare you can create rules to redirect http to https traffic. 

https://support.cloudflare.com/hc/en-us/articles/200170536-How-do-I-redirect-all-visitors-to-HTTPS-SSL-

Can you implement this and then close out the ticket.

**Comment by jamesmontemagno** [comment]
![image](https://cloud.githubusercontent.com/assets/1676321/22041530/13c50e74-dcbc-11e6-8c54-de8b95c144bd.png)
