### ISSUE TITLE
Authors with YouTube feeds get merged incorrectly

### ISSUE THREAD

**Issue by danielmonettelli** [planetxamarin/planetxamarin#633]
**Screenshots**

https://i.pinimg.com/originals/8a/6f/e3/8a6fe3b71ce0d275dfdf73119a970437.png

**Comment by Cheesebaron** [comment]
You are right, there seems to be an issue with all authors with YouTube feeds. Will have a look at this. Thank you for letting us know.

**Comment by Cheesebaron** [comment]
@danielmonettelli I hope this is fixed now. Can you please check next time you post a new video?

**Comment by danielmonettelli** [comment]
> @danielmonettelli I hope this is fixed now. Can you please check next time you post a new video?

Of course @Cheesebaron , if there is a problem, I will let you know, thank you very much for your time.
