### ISSUE TITLE
Argh forgot to put Xamarin tag in my post!

### ISSUE THREAD

**Issue by roubachof** [planetxamarin/planetxamarin#640]
I forgot to put the Xamarin tag in my new blog post on TaskLoaderView: 

https://www.sharpnado.com/taskloaderview-2-0-lets-burn-isbusy-true/

I corrected it later but it was already published...
Would it be possible to "force push" my new post on the planet's feed?

**Comment by jfversluis** [comment]
I see it’s indexed now, so all good!

![image](https://user-images.githubusercontent.com/939291/72426445-fe9d7280-3789-11ea-8742-7260675ee750.jpg)

**Comment by Cheesebaron** [comment]
@roubachof feed gets updated every hour :)
