### ISSUE TITLE
"Delpin Susai Raj" Blog posts are not showing

### ISSUE THREAD

**Issue by egbakou** [planetxamarin/planetxamarin#642]
**Describe the bug**
When click on "View original post", the feed is downloaded instead of going to the blog post.

**To Reproduce**
1. Go to https://www.planetxamarin.com/preview
2. Click on 'View original post' (Only for **Delpin Susai Raj** )
3. See error

**Expected behavior**
The browser downloads the Feed of the website instead of opening the post link.

**Comment by Cheesebaron** [comment]
We don't control which URL's an author's feed entries point to. It is up to them to fix it. Can't fix it from our perspective.

**Comment by egbakou** [comment]
Okay.
