### ISSUE TITLE
Fix CI/CD

### ISSUE THREAD

**Issue by jamesmontemagno** [planetxamarin/planetxamarin#650]
Right now I have turned off CD due to some issues. I will fix, for now I will publish manually.

**Comment by jamesmontemagno** [comment]
Current build command is:

```
/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\" /p:Configuration=$(BuildConfiguration)
```

and I just use web deploy with $(System.DefaultWorkingDirectory)\**\*.zip however seems to have issues for some reason.... not sure why.

**Comment by jamesmontemagno** [comment]
Created a new dev slot that all master builds will go to so we can monitor:
https://communityplanetxamarin-dev.azurewebsites.net/

I then can swap to prod when we need to go live

**Comment by jamesmontemagno** [comment]
also, now building against VS 2019 instead of VS 2017

**Comment by Cheesebaron** [comment]
I was working a bit on moving to ASP.NET Core + Blazor static pages the other day. Will take a fair bit of work. All the feed parsing stuff is plug and play though.

**Comment by jamesmontemagno** [comment]
Setup github actions ;)
