### ISSUE TITLE
Planet Xamarin does not display new authors

### ISSUE THREAD

**Issue by saamerm** [planetxamarin/planetxamarin#663]
**Describe the bug**
It seems like all the authors that were added to master since March 31 are not reflected in the [authors list page](https://www.planetxamarin.com/authors) (map or list)

**To Reproduce**
1. Go to the author's[ list page](https://www.planetxamarin.com/authors)
2. Click on the Search bar and type any of the names from the picture below, like "Mike Grant
3. You will see no search results
4. On the map, zoom into Toronto, Canada.
5. You should be able to see 4 people, but it only shows 3

**Expected behavior**
The added names should display in the list and searchable on the map

**Screenshots**
As you can see in the list of merged PR's these added authors do not appear
<img width="747" alt="image" src="https://user-images.githubusercontent.com/8262287/82019986-33490a00-9656-11ea-812b-6a0af2ec0223.png">

No search results displayed for "Mike Grant"
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/8262287/82064664-1551c880-969b-11ea-99ac-ec1f59c5404f.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: Latest 

**Additional context**
This could mean that the other merged changes are also not reflecting in the application. Or it could mean that the application has cached the list of authors, and it is not refreshing that cache.

**Comment by jamesmontemagno** [comment]
I have to push out a new version manually currently

**Comment by jamesmontemagno** [comment]
published

**Comment by saamerm** [comment]
Awesome thanks a lot! :)
