### ISSUE TITLE
MergeConflict Feed RSS Error

### ISSUE THREAD

**Issue by saamerm** [planetxamarin/planetxamarin#665]
**Describe the bug**
If you compare other feeds with the MergeConflict RSS feed, you will notice that the MergeConflict feed has an [error](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmergeconflict.fireside.fm%2Frss) 

**How I figured it out:**
In the [Azure pipeline test details](https://dev.azure.com/jamesmontemagno/Planet%20Xamarin/_build/results?buildId=1741&view=results) for [my PR](https://github.com/planetxamarin/planetxamarin/pull/664), the "Test Assemblies" job was failing. Upon reading further it mentions: 

> Feed(s) for Merge Conflict  @  is null or empty @https://mergeconflict.fireside.fm/rss 

This seems to be the only feed that was failing. So I took that feed and I put it into an rss validator, and it failed the validation. I validated that the RSS validator worked by using a valid RSS feed URL as well

**Expected behavior**
All Tests should pass, MergeConflic RSS feed should be valid

**Screenshots**
Here's a screenshot from the Azure pipeline log:
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/8262287/82072423-b9d90800-96a5-11ea-9d66-99c50ff1bc78.png">

**Additional context**
Please let me know if I can fix it in a certain way and I can do it right away @jamesmontemagno

**Comment by jamesmontemagno** [comment]
Updated

**Comment by saamerm** [comment]
@jamesmontemagno 
I tried the new URL you provided "https://feeds.fireside.fm/mergeconflict/rss", but it still seems to fail for some RSS feed checkers, just like it did before and could still be failing the Check. You can try these but it looks like similar reasons as it was failing before:
* https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ffeeds.fireside.fm%2Fmergeconflict%2Frss
* http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Ffeeds.fireside.fm%2Fmergeconflict%2Frss

**Comment by jamesmontemagno** [comment]
The tests just validate that the feed returns something.

Rss validiators aren't super usefull for podcasts. Joe rogen's doesn't technically validate: http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fwww.joeroganexp.joerogan.libsynpro.com%2Frss

**Comment by saamerm** [comment]
Ah yes it just passed the test for your feed this time https://dev.azure.com/jamesmontemagno/Planet%20Xamarin/_build/results?buildId=1744&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=023e7c10-1b10-57e0-8fcd-191cc0e0ded0&l=581

**Comment by jamesmontemagno** [comment]
Yeah, weird cause it worked locally. I think because it had a redirect it didn't like it maybe....
