### ISSUE TITLE
Incorrect author Name and Image on Preview page

### ISSUE THREAD

**Issue by saamerm** [planetxamarin/planetxamarin#666]
**Describe the bug**
For some reason https://www.planetxamarin.com/preview is displaying two of my articles on the page with "Ahmed Fouad"'s name and picture. I have been trying to scratch my head around it, but I'm not able to figure out why this might be happening. Any takes?

If you tap on "View Original Post", it does take me to the right blog post.

**To Reproduce**
1. Go to https://www.planetxamarin.com/preview
2. View the author's image and name of articles with titles "Start building with NFC RFID tags on iOS & Android using Xamarin today!" or, "Quick ways to free space on your Xamarin Mac machine"
3. Scroll down to the article '7 ways to improve code quality in c# using option type' by Ahmed Fouad and that one works fine. It just seems to happen with my articles
4. Also, when I review the Authors list page, I appear there perfectly with my name, picture and location.

**Expected behavior**
The author's image shouldn't be Ahmed's face, and the name should say "Saamer Mansoor"

**Screenshots**
Screenshot of my article showing Ahmed's name and picture:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/8262287/82105168-dac24d00-96e7-11ea-9279-61da9f1fbce1.png">
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version Latest >13

**Additional context**
I tried to go through the code for all instances of me and Ahmed, and there doesn't seem to be anything standing out to me.

**Comment by jamesmontemagno** [comment]
The reason here is because multiple blogs are on medium... and it picks based on host....

**Comment by jamesmontemagno** [comment]
Cleaned up, probably not the best solution... but works lols

**Comment by saamerm** [comment]
The website still shows the same. But when I built the application on a Windows I was able to verify that the changes in your last commit did fix it 
Thanks for your time!

**Comment by jamesmontemagno** [comment]
I just need to push a new build up :)
