### ISSUE TITLE
Renaming to MAUI

### ISSUE THREAD

**Issue by saamerm** [planetxamarin/planetxamarin#669]
As we all know, Xamarin has been [renamed to MAUI](https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/), and that raises a few questions:

* Do we have a timeline as to when we want to start changing some of the references on the website? Or should we do it right away?
* Also, how do we want to change it? Just replace Xamarin with MAUI where appropriate, and add an explanation that Xamarin is renamed to MAUI on the homepage? Or should just say "MAUI (Xamarin)" everywhere for now?

**Comment by Cheesebaron** [comment]
Ehm. No. _Xamarin_ hasn't been renamed to .NET MAUI. Xamarin.Forms has.

Xamarin.iOS, Xamarin.Android and the other variants are going to be part of .NET 6. However, _currently_ no plans on changing anything.

**Comment by saamerm** [comment]
Ah true @Cheesebaron we should probably close this then
