### ISSUE TITLE
PlanetXamarin Preview and Twitter account stopped working

### ISSUE THREAD

**Issue by saamerm** [planetxamarin/planetxamarin#691]
**Describe the bug**
There seems to be an issue since September 1st that was possibly caused during an error while merging of Pull Requests. The preview page of the website returns an error and the Twitter account has stopped tweeting

**To Reproduce**
Steps to reproduce the website behavior:
1. Go to the [Preview page](https://www.planetxamarin.com/preview) on the PlanetXamarin website you will see an error as shown:
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/8262287/93021596-78079200-f5b1-11ea-9f27-3383e1942b81.png">

Steps to reproduce the twitter behavior:
1. Go to the PlanetXamarin [twitter page](https://twitter.com/PlanetXamarin) and you'll see that the last tweet was made on September 1st 
<img width="618" alt="image" src="https://user-images.githubusercontent.com/8262287/93021617-8c4b8f00-f5b1-11ea-94de-961e9d633cdf.png">

**Expected behavior**

* For the website, you expect to see the preview page without the error
* For the twitter page, you expect to see a constant flow of new tweets

**Screenshots**
* 2 Provided above

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 13.1

**Comment by mike-grant** [comment]
The logs link indicates that it is a problem with one specific blog.

"No connection could be made because the target machine actively refused it 185.224.137.187:443" and then the detail for that exception

```
System.Exception: Leomaris Reyes's feed of https://askxammy.com/feed failed to load. ---> Firehose.Web.Infrastructure.FeedReadFailedException: Loading remote syndication feed failed ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 185.224.137.187:443
```

**Comment by saamerm** [comment]
@mike-grant thank you! How did you manage to see those logs? 

Using a [feed validator](https://validator.w3.org/feed/), I put in "https://askxammy.com/feed" and it gave me this error: 
Server returned [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727) 

@LeomarisReyes could you please look into this ASAP?

**Comment by LeomarisReyes** [comment]
Hi @saamerm ! I was testing and I see that everything is working correctly. Verifying, I removed the Telerik and ThomasBandt classes from csproj and the error was gone.

Testing by going directly to https://askxammy.com/feed , it worked for me without problems.

**Comment by saamerm** [comment]
@LeomarisReyes thanks for jumping on it. I see that the preview is now working

**Comment by saamerm** [comment]
@LeomarisReyes your feed is down again, and so is the preview page. -.-

**Comment by saamerm** [comment]
@Cheesebaron what can I do to prevent the failure from one unsuccessful feed read in the NewCombinedFeedSource class?

**Comment by LeomarisReyes** [comment]
@saamerm  Could you confirm again please? because I'm checking and both my feed and my blog are up 🥺

**Comment by saamerm** [comment]
@LeomarisReyes still down. 
Just go to https://validator.w3.org/feed/ and put in https://askxammy.com/feed and see what it says

Alternatively you can check out the logs https://www.planetxamarin.com/logs to see where it mentions `System.Exception: Leomaris Reyes's feed of https://askxammy.com/feed failed to load.`

**Comment by Cheesebaron** [comment]
@saamerm feed is valid and loads. It is just that often the server rejects the requests, according to the logs. This won't bring down the site.

**Comment by saamerm** [comment]
@Cheesebaron then how can we get www.planetxamarin.com/preview to work again?

**Comment by Cheesebaron** [comment]
@saamerm a good start would be to actually debug the issue 😃

**Comment by LeomarisReyes** [comment]
@saamerm the bug is fixed!

<img width="1590" alt="image" src="https://user-images.githubusercontent.com/35940594/93845247-25436f80-fc6e-11ea-9665-20941de393d8.png">
