### ISSUE TITLE
Build failed with some rss feeds issues

### ISSUE THREAD

**Issue by SylvainMoingeon** [planetxamarin/planetxamarin#702]
**Describe the bug**
Build failed.

**Expected behavior**
Build don't fail. 

**Additional context**
Some rss feeds seem to have issues : UnitTest.AuthorsTest.All_Authors_Have_Secure_And_Parsable_Feed [FAIL]

**Question**
Does that prevent the publication of new authors ?

**Comment by Cheesebaron** [comment]
No
