### ISSUE TITLE
SylvainMoingeon don't appear on authors page and in the feed

### ISSUE THREAD

**Issue by SylvainMoingeon** [planetxamarin/planetxamarin#703]
**Describe the bug**
My pull requests were merged 7 days ago (#698 and #701), but my feed nor my author card appear on Planet Xamarin.
Is there any issues with my feed or my author class ?

**To Reproduce**
Search for "Sylvain" on authors page.
Subscribe to the feed, you cant' find my blog posts 

**Expected behavior**
See my blog posts in the Planet Xamarin feed.
Find me as author in the authors page.

My feed seems valid : 
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.sylvainmoingeon.fr%2Ffeed.xml

![feed_validator](https://user-images.githubusercontent.com/7262188/99643121-9aec7180-2a4c-11eb-902d-c2c8c2732de5.png)

**Comment by Cheesebaron** [comment]
Code hasn't been deployed yet 😄

**Comment by SylvainMoingeon** [comment]
Ok, I thought CI/CD would deploy it after the merge. 😅

**Comment by Cheesebaron** [comment]
Sorry, that part is broken right now, so @jamesmontemagno deploys manually once in a while. Sorry for the wait.

**Comment by SylvainMoingeon** [comment]
Hello @jamesmontemagno,  when do you plan to deploy ?
I'm looking forward to joining the planetXamarin community. 🙂
