### ISSUE TITLE
Checox feed fails

### ISSUE THREAD

**Issue by sact1909** [planetxamarin/planetxamarin#717]
**Describe the bug**
I have a problem with my feeds in the Preview tab, I made two posts this week and there is not one of them there, I tried running the Xamarin project on my computer, and it shows my posts.

**To Reproduce**
1. Go to 'https://www.planetxamarin.com/'
2. Click on 'Preview'
3. Scroll down to 'til end'
4. You won see any post from my blog 

**Expected behavior**
when you click on the preview tab, my last post being there.

**Comment by Cheesebaron** [comment]
Doesn't seem that the latest authors have been deployed yet, which is why you don't see them.

**Comment by sact1909** [comment]
Oh, Nice, sorry for this issue, I didn't know :D thanks
