### ISSUE TITLE
As an author enrolled in this esteemed community service, but unfortunately, none of my articles are available in the feed

### ISSUE THREAD

**Issue by egvijayanand** [planetxamarin/planetxamarin#728]
**Describe the bug**
As an author enrolled in this esteemed community service, but unfortunately, none of my articles are available in the feed, details are as mentioned below.

**To Reproduce**
Blog details: https://egvijayanand.in/
Feed details: https://egvijayanand.in/feed/
Author Name: Vijay Anand E G

**Expected behavior**
Feeds suppose to contain the posts that are also from my blog (of course, those are relevant to Xamarin only)

**Screenshots**
NA

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
NA

**Comment by jamesmontemagno** [comment]
I need to push out a new build, I will do that this weekend.

**Comment by egvijayanand** [comment]
Hi @jamesmontemagno,

Thanks for the update.

**Comment by jamesmontemagno** [comment]
all done
