### ISSUE TITLE
Should we, by default apply IFilterMyBlogPosts and allow people to override?

### ISSUE THREAD

**Issue by ghuntley** [planetxamarin/planetxamarin#78]
Currently:
- All posts are syndicated.
- It seems everyone is using the same logic...

```csharp
return item.Title.Text.ToLowerInvariant().Contains("xamarin") && item.Categories.Any(c => c.Name.ToLowerInvariant().Equals("xamarin"));
```

Proposed:
- By default, we apply the above logic or similar to everyone.
- That interface (or similar) is used by authors to opt out of our defaults, allowing authors to implement their own logic. Example - weeklyxamarin/gonemobile/xamarinshow/mergeconflict should _always_ be included because they are never off-topic regardless of tag.

**Comment by jfversluis** [comment]
Hm I think we could do something like this, I would be hesitant to use the actual one you put down here. This means the title should have Xamarin in it _and_ one category should be Xamarin. I think I have a category Xamarin.Forms and usually don't do multiple categories and surely not all my posts have Xamarin in the title.

Or maybe they do.. Anyhow I'm afraid if we do this things become less transparent and people will get confused as to why some posts aren't shown.

Maybe we could tweak it a bit.

**Comment by Cheesebaron** [comment]
This is done as proposed by @ghuntley in #406 

For sites that are purely Xamarin content they can simply implement `IFilterMyBlogPosts` and return `true`.
