### ISSUE TITLE
What feeds to be want to expose?

### ISSUE THREAD

**Issue by ghuntley** [planetxamarin/planetxamarin#9]
* An endpoint that is everyone in the firehose. (yes/no)?
* An endpoint that is just Xamarin employees. (yes/no)?
* An endpoint that is just Xamarin MVPs. (yes/no)?
* An endpoint that is just Community. (yes/no)?

What about i18n? #16

**Comment by ghuntley** [comment]
See also #16 for the topic of i18n. We will most likely need to expose way to include or filter out languages.

**Comment by jamesmontemagno** [comment]
I have all of the older blogger information that I can import from the old planet xamarin btw!!!

Since this is public I guess we shouldn't show the email address in the github repo for Gravatar we should use the Hash value....

**Comment by jamesmontemagno** [comment]
Closing this out for sure, we is good

**Comment by ghuntley** [comment]
Nah; at this stage we only have single feed. Do we want to expose multiple feeds? What about #16 ?

**Comment by jamesmontemagno** [comment]
Ohhhhhh I see what you are saying :) I read it wrong.

**Comment by jamesmontemagno** [comment]
- An endpoint that is everyone in the firehose. (yes/no)? Yes (I need this for autoposting)

For the following 3 I say we do each or we do none. 
- An endpoint that is just Xamarin employees. (yes/no)? 
- An endpoint that is just Xamarin MVPs. (yes/no)?
- An endpoint that is just Community. (yes/no)?

I think we can just do one master and that is fine, can always add more later if needed.

**Comment by ghuntley** [comment]
#76 was just merged which defines the base route as `/feed/`

If we decide to add more feeds; maybe the best way to do it is with an ActionFilter or UrlParamaters.

i.e. `/feed/?i18n=en-US` or `/feed/?employees=true&community=false`

**Comment by jfversluis** [comment]
@Cheesebaron with the logistics we now have in place we could decide to extend it with this?

**Comment by Cheesebaron** [comment]
Sure. Right now we just group by the `FeedLanguage` property on the author class, but we could do more. The caching mechanism from BlogMonster, seems to eat anything, so we can make a class to help cache and group by specific parameters.
