### ISSUE TITLE
Restrict the default feed (thus Twitter/Facebook as well) to English?

### ISSUE THREAD

**Issue by ghuntley** [planetxamarin/planetxamarin#94]
Then provide a way for user to opt-in on their personal RSS feed that they understand Spanish, French, German, Mandarin, Arabic, Japanese, etc

See also #16

**Comment by jamesmontemagno** [comment]
Probably a good idea... not sure how to handle it though... Does each author need to put in a country code?

**Comment by jfversluis** [comment]
In the RSS2 [specification](https://validator.w3.org/feed/docs/rss2.html#optionalChannelElements) there is a language tag, but it's optional so a lot of the providers probably won't fill it, but it is some factor we could rule in?

**Comment by jamesmontemagno** [comment]
I think we need to think about this as it is a bit strange to have a mixture of languages. We either need a subdomain with an RSS for each language, selectors, or something... not sure.

**Comment by Cheesebaron** [comment]
I just vented the idea again with @jfversluis on Slack. I think the easiest way to go about this is to add another Property in the `IAmACommunityMember` interface, which denotes the language. Preferably in some standardized way like ISO 639 1 or 2. Then have the newly added UnitTests validate this Property to see if it is a valid language.

Then when this is added, we can start generate feeds by looking at which languages we have in those properties.

**Comment by jfversluis** [comment]
To not break the current working of PX we've decided not to filter the feed by default. However, there is now the ability to filter the feed for whoever might want that. All this goodness implemented in #429.

@jamesmontemagno if needed, you could now make the IFTTT feed to Twitter or Facebook English only by appending `lang=en`, like so: https://www.planetxamarin.com/feed?lang=en
