### ISSUE TITLE
Maintainer and Community Guidelines

### ISSUE THREAD

**Issue by ghuntley** [planetxamarin/planetxamarin#95]
We have a code of conduct which is a great start but no guidelines for:
- Removing authors for serious CoC violations.
- Disabling authors when their filters malfunction (i.e. non-xamarin content is syndicated) and how to communicate with the authors
- Disabling authors when they syndicate non-english in the english feed - see #16 #78  
- What is the min acceptable quality we look for before adding an author? We want to be inclusive to people just getting started but at the same time want posts that are a higher quality than StackOverflow answers.
- Documented that _anyone of the authors/maintainers_ can submit a PR to disable another author if they believe the content is not at an acceptable level but the process must be done tactfully.

**Comment by jfversluis** [comment]
Great! I think that we as maintainers should act as gate keepers as well. I already check if the feed URL is available and what the site is that is provided, etc. So more or less the basic sanity check.
If we just agree on upholding that we will be fine for the most part.

The tricky part IMHO is to detect blogs/authors that start to fall out of the CoC.
